[package]
name = "service-robot"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
regex = "1.11.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench_1"
harness = false
